In [1]:
import time
from importlib.resources import files
import numpy as np
from Consensus import *

In [2]:
INPUT_TREE_PATH = files("Consensus.sample10").joinpath(f"lowsample3.tre")
input_trees = TreeList_with_support.get(path = INPUT_TREE_PATH, schema = "newick")
majority = input_trees.majority_rule_consensus()

In [3]:
stdg = STDGreedyConsensus(input_trees)

Creating Bipartition List etc... time passed : 0.04008173942565918
TIME_number_of_independent_bipartitions:  31
TIME_Creating_DIST: 0.00
TIME_Creating_TD: 0.18


In [4]:
stdg.BipartitionP

array([3, 2, 3, 2, 4, 3, 2, 2, 2, 4, 4, 2, 2, 4, 5, 3, 4, 4, 4, 5, 4, 4,
       5, 4, 5, 2, 4, 3, 5, 2, 2])

In [5]:
stdg.DIST.shape

(32, 32)

In [6]:
stdg.n_bipartitions

31

In [7]:
over_bipartitions = np.zeros(stdg.n_bipartitions)
for i in range(stdg.n_bipartitions):
    over_count = 0
    for j in range(stdg.n_bipartitions):
        if(stdg.DIST[i,j] < stdg.BipartitionP[i] - 1): over_count += 1
    over_bipartitions[i] = over_count/stdg.n_bipartitions

In [8]:
over_bipartitions

array([0.25806452, 0.03225806, 0.19354839, 0.03225806, 0.5483871 ,
       0.19354839, 0.03225806, 0.03225806, 0.03225806, 0.32258065,
       0.25806452, 0.03225806, 0.03225806, 0.25806452, 0.80645161,
       0.16129032, 0.35483871, 0.38709677, 0.38709677, 0.74193548,
       0.41935484, 0.4516129 , 0.77419355, 0.41935484, 0.77419355,
       0.03225806, 0.35483871, 0.09677419, 0.48387097, 0.03225806,
       0.03225806])

In [9]:
np.zeros(len(stdg.BipartitionList))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
len(stdg.BipartitionList)

31

In [20]:
ASTRAL_INPUT_TREE_PATH = files("Consensus.sample100").joinpath(f"lowsample3.tre")
ASTRAL_TREE_PATH = files("Consensus.sample100").joinpath(f"low_astral3.tre")

In [24]:
astral_input_trees=TreeList_with_support.get(path = ASTRAL_INPUT_TREE_PATH, schema = "newick")
astral_tree = Tree_with_support.get(path = INPUT_TREE_PATH, schema = "newick",taxon_namespace = astral_input_trees.taxon_namespace)

In [25]:
astral_std = astral_tree.STD_greedy_pruning(astral_input_trees, normalized=True,time_flag =True)

computing transfer_support...
computing transfer_support for the other side...
current risk: 103029.24234042017
current risk: 102030.24234042017
current risk: 101082.25332559513
current risk: 100161.78776170856
bad second support 0.07692307692307687 0.05128205128205132
18889465931461400985600
142111877890048 38334640028177661952 38370668825196625920 0
bad second support 0.06521739130434778 0.04347826086956519
2417851639229241169543168
142111877890048 38334640028177661952 38370668825196625920 0
bad second support 0.06382978723404253 0.04255319148936165
2417851639229249759477760
142111877890048 38334640028177661952 38370668825196625920 0
bad second support 0.06382978723404253 0.04255319148936165
7253554917687757868367872
142111877890048 38334640028177661952 38370668825196625920 0
bad second support 0.07499999999999996 0.050000000000000044
4854592744389978099810304
142111877890048 38334640028177661952 38370668825196625920 0
bad second support 0.07317073170731703 0.04878048780487809
145259